export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
